-- CAPACITY CONNECT - IMD / MoES (SIH 2026, PS ID 26075)
-- Cloud demo dataset. Run AFTER supabase/schema.sql.
-- Built with dollar-quoted literals: the entire file contains ZERO single
-- quotes, so quote/format mangling cannot corrupt string values.
-- Idempotent: clears the demo tables and reloads fresh data on every run.

begin;

-- ===================== CLEAR DEMO TABLES ============================
-- (children first to satisfy the foreign keys)
delete from public.homepage_bulletins;
delete from public.trainee_competency_scores;
delete from public.evaluation_logs;
delete from public.exam_questionnaires;
delete from public.modules;
delete from public.courses;
delete from public.user_profiles;

-- ===================== 1.git USER PROFILES =============================
insert into public.user_profiles (
  employee_id, name, email, role, designation, station_location, specialty,
  qualifications, work_experience, interests, approved_by_admin, profile_submitted, profile_password
) values
  ($s$IMD/OPS/RMENON-03$s$, $s$Dr. Rajeshwari Menon$s$, $s$rajeshwari.menon@imd.gov.in$s$, $s$Trainee$s$, $s$Meteorologist A$s$, $s$Regional Meteorological Centre, New Delhi$s$, $s$$s$, $s${"degree":"M.Sc. Meteorology","year":2018,"institute":"IIT Delhi"}$s$, $s${"years":6,"roles":["Forecaster Grade-II","Operational Meteorologist"]}$s$, array[$s$Satellite Meteorology$s$,$s$Cyclone Tracking$s$,$s$Nowcasting$s$], true, true, $s$demo123$s$),
  ($s$IMD/HQ/SRAO-15$s$, $s$Dr. Someshwar Rao$s$, $s$s.rao@imd.gov.in$s$, $s$Trainer$s$, $s$Scientist-F$s$, $s$IMD Head Office, New Delhi$s$, $s$Numerical Weather Prediction & Radar Meteorology$s$, $s${"degree":"Ph.D. Atmospheric Physics","year":2013,"institute":"IISc Bangalore"}$s$, $s${"years":12,"roles":["Forecaster Grade-II","Training Coordinator"]}$s$, array[$s$Satellite Meteorology$s$,$s$Severe Weather Forecasting$s$], true, true, $s$demo123$s$),
  ($s$IMD/HQ/MMOHAP-01$s$, $s$Dr. M. Mohapatra$s$, $s$m.mohapatra@imd.gov.in$s$, $s$Admin$s$, $s$Director General of Meteorology$s$, $s$IMD Head Office, New Delhi$s$, $s$$s$, $s${"degree":"Ph.D. Meteorology","year":2005,"institute":"IIT Delhi"}$s$, $s${"years":20,"roles":["Scientist-E","Divisional Head Training"]}$s$, array[$s$Capacity Building$s$,$s$Policy$s$,$s$Research$s$], true, true, $s$demo123$s$),
  ($s$IMD/PUNE/PB-23$s$, $s$Prabha Deshpande$s$, $s$prabha@imd.gov.in$s$, $s$Trainee$s$, $s$Scientific Assistant$s$, $s$IMD Office, Pune$s$, $s$$s$, $s${"degree":"M.Sc. Meteorology","year":2021,"institute":"IITM Pune"}$s$, $s${"years":2,"roles":["Rain Gauge Network Operator"]}$s$, array[$s$Agro-Meteorology$s$,$s$Hydrology$s$], true, true, $s$demo123$s$),
  ($s$IMD/CWC/AB-31$s$, $s$Arjun Bhattacharya$s$, $s$arjun@imd.gov.in$s$, $s$Trainee$s$, $s$Meteorologist-A$s$, $s$Cyclone Warning Centre, Kolkata$s$, $s$$s$, $s${"degree":"M.Sc. Ocean & Atmospheric Sci","year":2019,"institute":"IIT Bhubaneswar"}$s$, $s${"years":5,"roles":["Cyclone Watch Assistant"]}$s$, array[$s$Cyclone Tracking$s$,$s$Storm Surge Modelling$s$], true, true, $s$demo123$s$),
  ($s$IMD/MUM/RL-18$s$, $s$Lakshmi Raman$s$, $s$lakshmi@imd.gov.in$s$, $s$Trainee$s$, $s$Scientific Assistant$s$, $s$Regional Meteorological Centre, Mumbai$s$, $s$$s$, $s${"degree":"M.Sc. Physics","year":2022,"institute":"University of Mumbai"}$s$, $s${"years":1,"roles":["Radar Data Logger"]}$s$, array[$s$Doppler Radar$s$,$s$Nowcasting$s$], true, true, $s$demo123$s$),
  ($s$IMD/HYD/VK-55$s$, $s$Vikram Reddy$s$, $s$vikram@imd.gov.in$s$, $s$Trainer$s$, $s$Meteorologist-B$s$, $s$Cyclone EWS, Hyderabad$s$, $s$Cyclone Warning Systems & Doppler Radar$s$, $s${"degree":"M.Tech Atmospheric Science","year":2015,"institute":"IIT Madras"}$s$, $s${"years":9,"roles":["Forecaster Grade-I","Radar Scientist"]}$s$, array[$s$Cyclone Warning Systems$s$,$s$AI in Nowcasting$s$], true, true, $s$demo123$s$),
  ($s$IMD/AHM/SP-77$s$, $s$Sonali Parmar$s$, $s$sonali@imd.gov.in$s$, $s$Trainee$s$, $s$Met Assistant$s$, $s$IMD Office, Ahmedabad$s$, $s$$s$, $s${"degree":"M.Sc. Environmental Science","year":2023,"institute":"Gujarat University"}$s$, $s${"years":1,"roles":["Ground Station Assistant"]}$s$, array[$s$Climate Services$s$,$s$Air Quality$s$], false, true, $s$demo123$s$),
  ($s$IMD/CHEN/RS-34$s$, $s$Rohit Subramaniam$s$, $s$rohit@imd.gov.in$s$, $s$Trainee$s$, $s$Scientific Assistant$s$, $s$Regional Meteorological Centre, Chennai$s$, $s$$s$, $s${"degree":"M.Sc. Marine Sciences","year":2021,"institute":"Annamalai University"}$s$, $s${"years":2,"roles":["Coastal Observatory Staff"]}$s$, array[$s$Tropical Cyclones$s$,$s$Storm Surge$s$], false, true, $s$demo123$s$),
  ($s$IMD/HQ/AP-09$s$, $s$Anita Joshi$s$, $s$anita.joshi@imd.gov.in$s$, $s$Trainer$s$, $s$Scientist-B$s$, $s$National Weather Forecasting Centre$s$, $s$Climate Modelling & Monsoon Dynamics$s$, $s${"degree":"Ph.D. Climatology","year":2016,"institute":"IIT Roorkee"}$s$, $s${"years":8,"roles":["Climate Modeller","Forecaster"]}$s$, array[$s$Climate Modelling$s$,$s$Monsoon Dynamics$s$], true, true, $s$demo123$s$)
on conflict (employee_id) do update set
  name = excluded.name,
  email = excluded.email,
  role = excluded.role,
  designation = excluded.designation,
  station_location = excluded.station_location,
  specialty = excluded.specialty,
  qualifications = excluded.qualifications,
  work_experience = excluded.work_experience,
  interests = excluded.interests,
  approved_by_admin = excluded.approved_by_admin,
  profile_submitted = excluded.profile_submitted,
  profile_password = excluded.profile_password;

-- ===================== 2. COURSES ===================================
insert into public.courses (
  title, description, category, duration, trainer_id, developed_competencies, materials_library
) values
  ($s$Numerical Weather Prediction & Model Guidance$s$, $s$Operational NWP concepts, model output statistics (MOS), ensemble forecasting, and bias correction for Indian monsoon systems.$s$, $s$Forecasting Science$s$, $s$16 hours$s$, (select id from public.user_profiles where employee_id = $s$IMD/HQ/SRAO-15$s$ limit 1), array[(select id from public.meteorological_competencies where competency_name = $s$Numerical Weather Prediction (NWP)$s$ limit 1),(select id from public.meteorological_competencies where competency_name = $s$Climate Modeling & Monsoon Dynamics$s$ limit 1)], $s${"lectures":[{"title":"NWP Fundamentals","video_url":"https://www.youtube.com/embed/"}],"presentations":["MOS-bias-correction.pdf"],"readings":["IMD-NWP-Bulletin-2025.pdf"]}$s$::jsonb),
  ($s$Satellite Remote Sensing for Weather Forecasting$s$, $s$INSAT-3DR and INSAT-3DS data interpretation, imager/sounder product usage, cloud classification, and precipitation estimation.$s$, $s$Remote Sensing$s$, $s$12 hours$s$, (select id from public.user_profiles where employee_id = $s$IMD/HQ/SRAO-15$s$ limit 1), array[(select id from public.meteorological_competencies where competency_name = $s$Satellite Remote Sensing & Data Interpretation$s$ limit 1),(select id from public.meteorological_competencies where competency_name = $s$Numerical Weather Prediction (NWP)$s$ limit 1)], $s${"lectures":[{"title":"INSAT Product Suite","video_url":"https://www.youtube.com/embed/"}],"presentations":["INSAT-3DR-operations.pdf"],"readings":["Satellite-Interpretation-Guide.pdf"]}$s$::jsonb),
  ($s$Radar Meteorology & Doppler Data Interpretation$s$, $s$DWR scan strategies, Doppler velocity patterns, reflectivity signatures, VIL tracking, and thunderstorm nowcasting workflows.$s$, $s$Radar Meteorology$s$, $s$14 hours$s$, (select id from public.user_profiles where employee_id = $s$IMD/HYD/VK-55$s$ limit 1), array[(select id from public.meteorological_competencies where competency_name = $s$Radar Meteorology & Doppler Data Interpretation$s$ limit 1),(select id from public.meteorological_competencies where competency_name = $s$Thunderstorm & Severe Weather Nowcasting$s$ limit 1)], $s${"lectures":[{"title":"DWR Product Interpretation","video_url":"https://www.youtube.com/embed/"}],"presentations":["Doppler-Mesoncyclone.pdf"],"readings":["DWR-Operational-SOP.pdf"]}$s$::jsonb),
  ($s$Cyclone Tracking & Warning Systems$s$, $s$Tropical cyclone genesis criteria, storm surge modelling, bulletin dissemination, and Cyclone Warning Centre operational protocols.$s$, $s$Severe Weather$s$, $s$18 hours$s$, (select id from public.user_profiles where employee_id = $s$IMD/HYD/VK-55$s$ limit 1), array[(select id from public.meteorological_competencies where competency_name = $s$Cyclone Tracking & Warning Systems$s$ limit 1),(select id from public.meteorological_competencies where competency_name = $s$Thunderstorm & Severe Weather Nowcasting$s$ limit 1)], $s${"lectures":[{"title":"CWC Operational Protocol","video_url":"https://www.youtube.com/embed/"}],"presentations":["Storm-Surge-Modelling.pdf"],"readings":["CWC-SOP-2024.pdf"]}$s$::jsonb),
  ($s$Agro-Meteorology & Crop-Weather Advisory$s$, $s$Crop-weather calendars, district-level advisories, soil moisture assessment, and agromet decision support for the Agriculture Ministry.$s$, $s$Applied Services$s$, $s$10 hours$s$, (select id from public.user_profiles where employee_id = $s$IMD/HQ/AP-09$s$ limit 1), array[(select id from public.meteorological_competencies where competency_name = $s$Agro-Meteorology & Crop Weather Advisory$s$ limit 1),(select id from public.meteorological_competencies where competency_name = $s$Hydrology & Rain Gauge Calibration$s$ limit 1)], $s${"lectures":[{"title":"Agromet Advisory Generation","video_url":"https://www.youtube.com/embed/"}],"presentations":["Crop-Weather-Calendar.pdf"],"readings":["Grameen-Mausam-Seva-Handbook.pdf"]}$s$::jsonb),
  ($s$Hydrology & Rain Gauge Calibration$s$, $s$Areal rainfall estimation, telemetric rain gauge maintenance, flood meteorology, and reservoir catchment monitoring.$s$, $s$Hydrometeorology$s$, $s$8 hours$s$, (select id from public.user_profiles where employee_id = $s$IMD/HQ/AP-09$s$ limit 1), array[(select id from public.meteorological_competencies where competency_name = $s$Hydrology & Rain Gauge Calibration$s$ limit 1),(select id from public.meteorological_competencies where competency_name = $s$Agro-Meteorology & Crop Weather Advisory$s$ limit 1)], $s${"lectures":[{"title":"Rain Gauge Calibration","video_url":"https://www.youtube.com/embed/"}],"presentations":["Areal-RAIN-Estimation.pdf"],"readings":["IMD-Observatory-Manual.pdf"]}$s$::jsonb),
  ($s$Climate Modeling & Monsoon Dynamics$s$, $s$Coupled climate models, IITM ensemble runs, monsoon onset/withdrawal diagnostics, and long-range forecast skill evaluation.$s$, $s$Climate Science$s$, $s$20 hours$s$, (select id from public.user_profiles where employee_id = $s$IMD/HQ/AP-09$s$ limit 1), array[(select id from public.meteorological_competencies where competency_name = $s$Climate Modeling & Monsoon Dynamics$s$ limit 1),(select id from public.meteorological_competencies where competency_name = $s$Numerical Weather Prediction (NWP)$s$ limit 1)], $s${"lectures":[{"title":"Monsoon Dynamics","video_url":"https://www.youtube.com/embed/"}],"presentations":["LRF-Verification.pdf"],"readings":["IITM-Ensemble-Guide.pdf"]}$s$::jsonb),
  ($s$Aviation Meteorology & SIGMET Issuance$s$, $s$METAR/TAF briefings, SIGMET/AIRMET criteria, wind shear and low visibility forecasting for airport operations.$s$, $s$Aviation$s$, $s$12 hours$s$, (select id from public.user_profiles where employee_id = $s$IMD/HQ/SRAO-15$s$ limit 1), array[(select id from public.meteorological_competencies where competency_name = $s$Aviation Meteorology & SIGMET Issuance$s$ limit 1),(select id from public.meteorological_competencies where competency_name = $s$Thunderstorm & Severe Weather Nowcasting$s$ limit 1)], $s${"lectures":[{"title":"SIGMET Issuance","video_url":"https://www.youtube.com/embed/"}],"presentations":["METAR-TAF-Decode.pdf"],"readings":["WMO-No.49-Annex3.pdf"]}$s$::jsonb)
on conflict (title) do nothing;

-- ===================== 3. MODULES ===================================
insert into public.modules (course_id, title, content_text, video_placeholder_url) values
  ((select id from public.courses where title = $s$Numerical Weather Prediction & Model Guidance$s$ limit 1), $s$NWP Framework & GFS/NCUM Systems$s$, $s$Introduction to operational global and regional NWP models used by IMD, grid resolution, and data assimilation requirements.$s$, $s$https://www.youtube.com/embed/$s$),
  ((select id from public.courses where title = $s$Numerical Weather Prediction & Model Guidance$s$ limit 1), $s$Model Output Statistics & Bias Correction$s$, $s$Applying MOS, climatological mean-bias removal, and station-specific calibration to raw model output.$s$, $s$https://www.youtube.com/embed/$s$),
  ((select id from public.courses where title = $s$Numerical Weather Prediction & Model Guidance$s$ limit 1), $s$Ensemble Forecasting for Monsoon$s$, $s$Interpreting IITM 10-member and 51-member ensembles, spread-skill relationship, and probability products.$s$, $s$https://www.youtube.com/embed/$s$),
  ((select id from public.courses where title = $s$Satellite Remote Sensing for Weather Forecasting$s$ limit 1), $s$INSAT-3DR Sounder Products$s$, $s$Temperature and humidity profiles, and their assimilation into regional models.$s$, $s$https://www.youtube.com/embed/$s$),
  ((select id from public.courses where title = $s$Satellite Remote Sensing for Weather Forecasting$s$ limit 1), $s$Cloud Classification & Precipitation Estimation$s$, $s$ISCCP-type classification, IMSRA precipitation estimation, and convective cell identification.$s$, $s$https://www.youtube.com/embed/$s$),
  ((select id from public.courses where title = $s$Radar Meteorology & Doppler Data Interpretation$s$ limit 1), $s$Doppler Velocity & Reflectivity Signatures$s$, $s$Velocity azimuth displays, mesocyclone signatures, and bright-band identification.$s$, $s$https://www.youtube.com/embed/$s$),
  ((select id from public.courses where title = $s$Radar Meteorology & Doppler Data Interpretation$s$ limit 1), $s$Thunderstorm Nowcasting Workflow$s$, $s$Cell tracking algorithms, VIL density thresholds, and short-range warning issuance.$s$, $s$https://www.youtube.com/embed/$s$),
  ((select id from public.courses where title = $s$Cyclone Tracking & Warning Systems$s$ limit 1), $s$Cyclone Genesis & Intensification$s$, $s$Genesis Potential Index, rapid intensification indicators, and T-number estimation.$s$, $s$https://www.youtube.com/embed/$s$),
  ((select id from public.courses where title = $s$Cyclone Tracking & Warning Systems$s$ limit 1), $s$Storm Surge & Coastal Inundation$s$, $s$ADcirc-based surge modelling and coastal community alerts.$s$, $s$https://www.youtube.com/embed/$s$),
  ((select id from public.courses where title = $s$Agro-Meteorology & Crop-Weather Advisory$s$ limit 1), $s$District Agromet Advisory Generation$s$, $s$Crop-weather calendar integration and advisory issuance via Grameen Mausam Seva.$s$, $s$https://www.youtube.com/embed/$s$),
  ((select id from public.courses where title = $s$Hydrology & Rain Gauge Calibration$s$ limit 1), $s$Telemetric Rain Gauge Calibration$s$, $s$Tipping bucket calibration, data validation, and transmission health checks.$s$, $s$https://www.youtube.com/embed/$s$),
  ((select id from public.courses where title = $s$Climate Modeling & Monsoon Dynamics$s$ limit 1), $s$Monsoon Onset & Withdrawal Diagnostics$s$, $s$Objective onset criteria, monsoon trough dynamics, and active/break spells.$s$, $s$https://www.youtube.com/embed/$s$),
  ((select id from public.courses where title = $s$Aviation Meteorology & SIGMET Issuance$s$ limit 1), $s$METAR/TAF & SIGMET Issuance$s$, $s$Aeronautical code decoding, SIGMET issuance criteria, and adverse weather thresholds.$s$, $s$https://www.youtube.com/embed/$s$)
on conflict (course_id, title) do update set content_text = excluded.content_text, video_placeholder_url = excluded.video_placeholder_url;

-- ===================== 4. EXAMS =====================================
insert into public.exam_questionnaires (course_id, questions, passing_score, submission_deadline) values
  ((select id from public.courses where title = $s$Numerical Weather Prediction & Model Guidance$s$ limit 1), $s$[{"id":"nwp-q1","question":"Which NWP model family is operationally used by IMD for regional forecasting?","options":["NCUM & GFS","ERA5 only","WRF-Lambert","CFSv2 only"],"correct":0},{"id":"nwp-q2","question":"What does MOS stand for in statistical post-processing?","options":["Model Output Statistics","Monsoon Onset System","Mean Observation Series","Multi-level Observation System"],"correct":0},{"id":"nwp-q3","question":"Bias correction for a station forecast primarily removes:","options":["Systematic model error","Random sensor error","Data assimilation noise","Human analysis error"],"correct":0},{"id":"nwp-q4","question":"An ensemble forecast spread that is too narrow indicates:","options":["Overconfidence in the solution","High forecast skill","Large observation gaps","Improper model resolution"],"correct":0},{"id":"nwp-q5","question":"Which product is essential for probabilistic rainfall forecasts?","options":["Ensemble probability charts","Single deterministic run","Raw MSLP chart","Satellite cloud imagery"],"correct":0}]$s$::jsonb, 60, $s$2026-10-31T23:59:59+05:30$s$),
  ((select id from public.courses where title = $s$Satellite Remote Sensing for Weather Forecasting$s$ limit 1), $s$[{"id":"sat-q1","question":"INSAT-3DR carries which radiometer essential for atmospheric profiling?","options":["Sounder","SAR","Scatterometer","Ozone mapper"],"correct":2},{"id":"sat-q2","question":"Rapidly growing cumulonimbus cells appear coldest (most intense) in which channel?","options":["Infrared window 10.5 um","Visible 0.65 um","Microwave 89 GHz","Shortwave IR 3.9 um"],"correct":0},{"id":"sat-q3","question":"The IMSRA product estimates which parameter over India?","options":["Rainfall intensity","Cloud top temperature","Sea surface temperature","Wind speed"],"correct":0},{"id":"sat-q4","question":"A water vapor channel (6.2 um) is most useful for detecting:","options":["Mid-tropospheric moisture","Ocean surface winds","Cloud base height","Surface temperature"],"correct":0},{"id":"sat-q5","question":"Nowcasting uses satellite imagery primarily for:","options":["Continuous monitoring of thunderstorm development","Climatological averages","Model initialization only","Long-range monsoon prediction"],"correct":0}]$s$::jsonb, 60, $s$2026-11-15T23:59:59+05:30$s$),
  ((select id from public.courses where title = $s$Radar Meteorology & Doppler Data Interpretation$s$ limit 1), $s$[{"id":"rad-q1","question":"A mesocyclone is identified in Doppler velocity data as:","options":["Opposing radial velocities adjacent to each other","Uniform flow","No echo region","Turbulent clear-air echo"],"correct":0},{"id":"rad-q2","question":"The bright band in reflectivity is caused by:","options":["Melting snowflakes","Strong updrafts","Hail stones","Clear air turbulence"],"correct":0},{"id":"rad-q3","question":"VIL (Vertically Integrated Liquid) is a proxy for:","options":["Storm severity","Cloud height","Surface wind","Dew point depression"],"correct":0},{"id":"rad-q4","question":"A hook echo signature is classically associated with:","options":["Supercell tornadogenesis","Downburst","Dust storm","Squall line"],"correct":0},{"id":"rad-q5","question":"Which radar product best tracks cell movement for nowcasting?","options":["Cell tracking & extrapolation","Base reflectivity only","VAD wind profile only","Single snapshot"],"correct":0}]$s$::jsonb, 60, $s$2026-11-30T23:59:59+05:30$s$),
  ((select id from public.courses where title = $s$Cyclone Tracking & Warning Systems$s$ limit 1), $s$[{"id":"cyc-q1","question":"The Genesis Potential Index (GPI) combines:","options":["Vorticity, humidity, vertical wind shear, SST","Pressure, temperature, humidity","Wind speed and direction","Cloud cover and rain rate"],"correct":0},{"id":"cyc-q2","question":"Rapid intensification is typically defined as wind increase of:","options":["55+ knots in 24 hours","5 knots in a week","10 knots in a month","20 knots in a day"],"correct":0},{"id":"cyc-q3","question":"The Dvorak T-number is estimated from:","options":["Satellite cloud patterns","Buoy measurements","Aircraft only","Radar velocity"],"correct":2},{"id":"cyc-q4","question":"Storm surge is primarily driven by:","options":["Surface wind stress and atmospheric pressure deficit","Ocean temperature","Sea wave period","Tidal currents only"],"correct":0},{"id":"cyc-q5","question":"CWC bulletins must be issued at minimum intervals of:","options":["3 hourly during alert period","24 hourly","Weekly","Once at landfall"],"correct":0}]$s$::jsonb, 60, $s$2026-12-15T23:59:59+05:30$s$),
  ((select id from public.courses where title = $s$Agro-Meteorology & Crop-Weather Advisory$s$ limit 1), $s$[{"id":"agro-q1","question":"Agromet advisories are primarily disseminated through:","options":["Grameen Mausam Seva (Kisan SMS)","Only print media","Aviation NOTAM","Marine forecasts only"],"correct":0},{"id":"agro-q2","question":"Crop weather calendars are aligned with:","options":["Crop growth phenophases","Financial quarters","Exam schedules","Public holidays"],"correct":0},{"id":"agro-q3","question":"Which index is used to assess crop moisture stress?","options":["Soil moisture deficit index","Heat index of buildings","Wet bulb globe only","Wind chill"],"correct":0},{"id":"agro-q4","question":"Sowing advisories depend most heavily on:","options":["Spatial rainfall forecast","Ocean wave height","Airport visibility","Sunspot activity"],"correct":0}]$s$::jsonb, 60, $s$2026-11-05T23:59:59+05:30$s$),
  ((select id from public.courses where title = $s$Hydrology & Rain Gauge Calibration$s$ limit 1), $s$[{"id":"hyd-q1","question":"A tipping bucket rain gauge records precipitation in increments of:","options":["0.5 mm typically","5 cm","50 mm","10 cm"],"correct":0},{"id":"hyd-q2","question":"Areal rainfall is best estimated from point gauges using:","options":["Thiessen polygons","Simple averaging of two stations","Satellite alone","No method needed"],"correct":0},{"id":"hyd-q3","question":"Telemetric gauge data validation flags:","options":["Sudden sensor jumps or stuck tips","Model output","CPC analysis","Climate normals"],"correct":0},{"id":"hyd-q4","question":"For flood meteorology, the most relevant forecast product is:","options":["Quantitative precipitation forecast (QPF)","Sea surface temperature chart","Atmospheric composition","UV index"],"correct":0}]$s$::jsonb, 60, $s$2026-11-20T23:59:59+05:30$s$),
  ((select id from public.courses where title = $s$Climate Modeling & Monsoon Dynamics$s$ limit 1), $s$[{"id":"clim-q1","question":"The Indian summer monsoon onset is declared based on:","options":["Objective criteria combining rainfall and dynamics","A single station reading","Calendar date only","Sea level only"],"correct":0},{"id":"clim-q2","question":"Active and break spells in monsoon are linked to:","options":["Monsoon trough oscillation","El Nino alone","Ozone depletion","Solar flares"],"correct":0},{"id":"clim-q3","question":"Long-range forecasts (LRF) for monsoon are issued:","options":["Seasonally ahead","Hourly","Every minute","After the season ends"],"correct":0},{"id":"clim-q4","question":"Coupled climate models are used to forecast:","options":["Seasonal-scale climate variations","Thunderstorms only","Fog events only","Lightning signatures only"],"correct":0}]$s$::jsonb, 60, $s$2026-12-01T23:59:59+05:30$s$)
on conflict (course_id) do update set
  questions = excluded.questions,
  passing_score = excluded.passing_score,
  submission_deadline = excluded.submission_deadline;

-- ===================== 5. COMPETENCY SCORES =========================
insert into public.trainee_competency_scores (trainee_id, competency_id, current_score, target_score, last_updated) values
  ((select id from public.user_profiles where employee_id = $s$IMD/OPS/RMENON-03$s$ limit 1), (select id from public.meteorological_competencies where competency_name = $s$Numerical Weather Prediction (NWP)$s$ limit 1), 47, 75, $s$2026-09-01T09:00:00+05:30$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/OPS/RMENON-03$s$ limit 1), (select id from public.meteorological_competencies where competency_name = $s$Satellite Remote Sensing & Data Interpretation$s$ limit 1), 71, 80, $s$2026-09-01T09:00:00+05:30$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/OPS/RMENON-03$s$ limit 1), (select id from public.meteorological_competencies where competency_name = $s$Radar Meteorology & Doppler Data Interpretation$s$ limit 1), 40, 75, $s$2026-09-02T10:15:00+05:30$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/OPS/RMENON-03$s$ limit 1), (select id from public.meteorological_competencies where competency_name = $s$Cyclone Tracking & Warning Systems$s$ limit 1), 52, 80, $s$2026-09-03T09:45:00+05:30$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/OPS/RMENON-03$s$ limit 1), (select id from public.meteorological_competencies where competency_name = $s$Agro-Meteorology & Crop Weather Advisory$s$ limit 1), 45, 70, $s$2026-09-04T14:30:00+05:30$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/OPS/RMENON-03$s$ limit 1), (select id from public.meteorological_competencies where competency_name = $s$Hydrology & Rain Gauge Calibration$s$ limit 1), 38, 70, $s$2026-09-05T11:20:00+05:30$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/OPS/RMENON-03$s$ limit 1), (select id from public.meteorological_competencies where competency_name = $s$Climate Modeling & Monsoon Dynamics$s$ limit 1), 60, 75, $s$2026-09-06T08:40:00+05:30$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/OPS/RMENON-03$s$ limit 1), (select id from public.meteorological_competencies where competency_name = $s$Thunderstorm & Severe Weather Nowcasting$s$ limit 1), 55, 80, $s$2026-09-07T10:50:00+05:30$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/OPS/RMENON-03$s$ limit 1), (select id from public.meteorological_competencies where competency_name = $s$Aviation Meteorology & SIGMET Issuance$s$ limit 1), 58, 70, $s$2026-09-08T09:10:00+05:30$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/OPS/RMENON-03$s$ limit 1), (select id from public.meteorological_competencies where competency_name = $s$Air Quality & Atmospheric Chemistry$s$ limit 1), 50, 65, $s$2026-09-09T14:25:00+05:30$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/PUNE/PB-23$s$ limit 1), (select id from public.meteorological_competencies where competency_name = $s$Numerical Weather Prediction (NWP)$s$ limit 1), 70, 75, $s$2026-09-02T10:00:00+05:30$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/PUNE/PB-23$s$ limit 1), (select id from public.meteorological_competencies where competency_name = $s$Satellite Remote Sensing & Data Interpretation$s$ limit 1), 64, 80, $s$2026-09-03T09:30:00+05:30$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/PUNE/PB-23$s$ limit 1), (select id from public.meteorological_competencies where competency_name = $s$Radar Meteorology & Doppler Data Interpretation$s$ limit 1), 55, 75, $s$2026-09-04T14:10:00+05:30$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/PUNE/PB-23$s$ limit 1), (select id from public.meteorological_competencies where competency_name = $s$Cyclone Tracking & Warning Systems$s$ limit 1), 60, 80, $s$2026-09-05T11:50:00+05:30$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/PUNE/PB-23$s$ limit 1), (select id from public.meteorological_competencies where competency_name = $s$Agro-Meteorology & Crop Weather Advisory$s$ limit 1), 58, 70, $s$2026-09-06T08:20:00+05:30$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/PUNE/PB-23$s$ limit 1), (select id from public.meteorological_competencies where competency_name = $s$Hydrology & Rain Gauge Calibration$s$ limit 1), 62, 70, $s$2026-09-07T10:35:00+05:30$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/PUNE/PB-23$s$ limit 1), (select id from public.meteorological_competencies where competency_name = $s$Climate Modeling & Monsoon Dynamics$s$ limit 1), 68, 75, $s$2026-09-08T09:40:00+05:30$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/PUNE/PB-23$s$ limit 1), (select id from public.meteorological_competencies where competency_name = $s$Thunderstorm & Severe Weather Nowcasting$s$ limit 1), 52, 80, $s$2026-09-09T14:15:00+05:30$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/PUNE/PB-23$s$ limit 1), (select id from public.meteorological_competencies where competency_name = $s$Aviation Meteorology & SIGMET Issuance$s$ limit 1), 60, 70, $s$2026-09-10T10:05:00+05:30$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/PUNE/PB-23$s$ limit 1), (select id from public.meteorological_competencies where competency_name = $s$Air Quality & Atmospheric Chemistry$s$ limit 1), 58, 65, $s$2026-09-10T15:30:00+05:30$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/CWC/AB-31$s$ limit 1), (select id from public.meteorological_competencies where competency_name = $s$Numerical Weather Prediction (NWP)$s$ limit 1), 72, 75, $s$2026-09-02T09:50:00+05:30$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/CWC/AB-31$s$ limit 1), (select id from public.meteorological_competencies where competency_name = $s$Satellite Remote Sensing & Data Interpretation$s$ limit 1), 68, 80, $s$2026-09-03T14:25:00+05:30$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/CWC/AB-31$s$ limit 1), (select id from public.meteorological_competencies where competency_name = $s$Radar Meteorology & Doppler Data Interpretation$s$ limit 1), 62, 75, $s$2026-09-05T11:30:00+05:30$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/CWC/AB-31$s$ limit 1), (select id from public.meteorological_competencies where competency_name = $s$Cyclone Tracking & Warning Systems$s$ limit 1), 74, 80, $s$2026-09-06T08:55:00+05:30$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/CWC/AB-31$s$ limit 1), (select id from public.meteorological_competencies where competency_name = $s$Agro-Meteorology & Crop Weather Advisory$s$ limit 1), 55, 70, $s$2026-09-07T10:40:00+05:30$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/CWC/AB-31$s$ limit 1), (select id from public.meteorological_competencies where competency_name = $s$Hydrology & Rain Gauge Calibration$s$ limit 1), 60, 70, $s$2026-09-08T14:05:00+05:30$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/CWC/AB-31$s$ limit 1), (select id from public.meteorological_competencies where competency_name = $s$Climate Modeling & Monsoon Dynamics$s$ limit 1), 66, 75, $s$2026-09-09T09:55:00+05:30$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/CWC/AB-31$s$ limit 1), (select id from public.meteorological_competencies where competency_name = $s$Thunderstorm & Severe Weather Nowcasting$s$ limit 1), 51, 80, $s$2026-09-10T11:20:00+05:30$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/CWC/AB-31$s$ limit 1), (select id from public.meteorological_competencies where competency_name = $s$Aviation Meteorology & SIGMET Issuance$s$ limit 1), 70, 70, $s$2026-09-11T08:30:00+05:30$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/CWC/AB-31$s$ limit 1), (select id from public.meteorological_competencies where competency_name = $s$Air Quality & Atmospheric Chemistry$s$ limit 1), 57, 65, $s$2026-09-11T13:45:00+05:30$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/MUM/RL-18$s$ limit 1), (select id from public.meteorological_competencies where competency_name = $s$Numerical Weather Prediction (NWP)$s$ limit 1), 61, 75, $s$2026-09-02T14:40:00+05:30$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/MUM/RL-18$s$ limit 1), (select id from public.meteorological_competencies where competency_name = $s$Satellite Remote Sensing & Data Interpretation$s$ limit 1), 74, 80, $s$2026-09-03T11:15:00+05:30$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/MUM/RL-18$s$ limit 1), (select id from public.meteorological_competencies where competency_name = $s$Radar Meteorology & Doppler Data Interpretation$s$ limit 1), 66, 75, $s$2026-09-04T09:25:00+05:30$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/MUM/RL-18$s$ limit 1), (select id from public.meteorological_competencies where competency_name = $s$Cyclone Tracking & Warning Systems$s$ limit 1), 68, 80, $s$2026-09-05T14:50:00+05:30$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/MUM/RL-18$s$ limit 1), (select id from public.meteorological_competencies where competency_name = $s$Agro-Meteorology & Crop Weather Advisory$s$ limit 1), 72, 70, $s$2026-09-06T10:10:00+05:30$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/MUM/RL-18$s$ limit 1), (select id from public.meteorological_competencies where competency_name = $s$Hydrology & Rain Gauge Calibration$s$ limit 1), 65, 70, $s$2026-09-07T08:35:00+05:30$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/MUM/RL-18$s$ limit 1), (select id from public.meteorological_competencies where competency_name = $s$Climate Modeling & Monsoon Dynamics$s$ limit 1), 63, 75, $s$2026-09-08T14:20:00+05:30$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/MUM/RL-18$s$ limit 1), (select id from public.meteorological_competencies where competency_name = $s$Thunderstorm & Severe Weather Nowcasting$s$ limit 1), 59, 80, $s$2026-09-09T10:45:00+05:30$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/MUM/RL-18$s$ limit 1), (select id from public.meteorological_competencies where competency_name = $s$Aviation Meteorology & SIGMET Issuance$s$ limit 1), 66, 70, $s$2026-09-10T09:00:00+05:30$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/MUM/RL-18$s$ limit 1), (select id from public.meteorological_competencies where competency_name = $s$Air Quality & Atmospheric Chemistry$s$ limit 1), 60, 65, $s$2026-09-11T11:30:00+05:30$s$)
on conflict (trainee_id, competency_id) do update set
  current_score = excluded.current_score,
  target_score = excluded.target_score,
  last_updated = excluded.last_updated;

-- ===================== 6. EVALUATION LOGS ===========================
insert into public.evaluation_logs (trainee_id, exam_id, score, percentage, completion_date, feedback_text) values
  ((select id from public.user_profiles where employee_id = $s$IMD/OPS/RMENON-03$s$ limit 1), (select e.id from public.exam_questionnaires e join public.courses c on c.id = e.course_id where c.title = $s$Satellite Remote Sensing for Weather Forecasting$s$ limit 1), 4, 80, $s$2026-09-02T10:30:00+05:30$s$, $s$Strong satellite interpretation. Revise sounder products.$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/OPS/RMENON-03$s$ limit 1), (select e.id from public.exam_questionnaires e join public.courses c on c.id = e.course_id where c.title = $s$Cyclone Tracking & Warning Systems$s$ limit 1), 3, 60, $s$2026-09-04T09:15:00+05:30$s$, $s$Marginal pass. Revisit storm surge modelling.$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/OPS/RMENON-03$s$ limit 1), (select e.id from public.exam_questionnaires e join public.courses c on c.id = e.course_id where c.title = $s$Numerical Weather Prediction & Model Guidance$s$ limit 1), 4, 80, $s$2026-09-06T15:40:00+05:30$s$, $s$Good grasp of ensemble probability products.$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/OPS/RMENON-03$s$ limit 1), (select e.id from public.exam_questionnaires e join public.courses c on c.id = e.course_id where c.title = $s$Agro-Meteorology & Crop-Weather Advisory$s$ limit 1), 3, 75, $s$2026-09-08T11:05:00+05:30$s$, $s$Advisory workflow clear; strengthen soil moisture index.$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/OPS/RMENON-03$s$ limit 1), (select e.id from public.exam_questionnaires e join public.courses c on c.id = e.course_id where c.title = $s$Radar Meteorology & Doppler Data Interpretation$s$ limit 1), 2, 40, $s$2026-09-09T14:20:00+05:30$s$, $s$Retake advised: Doppler velocity signatures need revision.$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/PUNE/PB-23$s$ limit 1), (select e.id from public.exam_questionnaires e join public.courses c on c.id = e.course_id where c.title = $s$Hydrology & Rain Gauge Calibration$s$ limit 1), 3, 75, $s$2026-09-05T14:10:00+05:30$s$, $s$Calibration workflow understood well.$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/PUNE/PB-23$s$ limit 1), (select e.id from public.exam_questionnaires e join public.courses c on c.id = e.course_id where c.title = $s$Agro-Meteorology & Crop-Weather Advisory$s$ limit 1), 4, 88, $s$2026-09-03T10:00:00+05:30$s$, $s$Excellent agromet advisory reasoning.$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/PUNE/PB-23$s$ limit 1), (select e.id from public.exam_questionnaires e join public.courses c on c.id = e.course_id where c.title = $s$Numerical Weather Prediction & Model Guidance$s$ limit 1), 3, 65, $s$2026-09-07T16:30:00+05:30$s$, $s$Adequate; ensemble interpretation to improve.$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/PUNE/PB-23$s$ limit 1), (select e.id from public.exam_questionnaires e join public.courses c on c.id = e.course_id where c.title = $s$Climate Modeling & Monsoon Dynamics$s$ limit 1), 2, 50, $s$2026-09-10T09:45:00+05:30$s$, $s$Retake required: monsoon onset diagnostics.$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/CWC/AB-31$s$ limit 1), (select e.id from public.exam_questionnaires e join public.courses c on c.id = e.course_id where c.title = $s$Cyclone Tracking & Warning Systems$s$ limit 1), 5, 92, $s$2026-09-04T08:50:00+05:30$s$, $s$Outstanding cyclone warning command.$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/CWC/AB-31$s$ limit 1), (select e.id from public.exam_questionnaires e join public.courses c on c.id = e.course_id where c.title = $s$Hydrology & Rain Gauge Calibration$s$ limit 1), 3, 66, $s$2026-09-06T12:25:00+05:30$s$, $s$Solid; refine QPF application.$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/CWC/AB-31$s$ limit 1), (select e.id from public.exam_questionnaires e join public.courses c on c.id = e.course_id where c.title = $s$Radar Meteorology & Doppler Data Interpretation$s$ limit 1), 4, 78, $s$2026-09-08T10:35:00+05:30$s$, $s$Strong mesocyclone identification.$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/CWC/AB-31$s$ limit 1), (select e.id from public.exam_questionnaires e join public.courses c on c.id = e.course_id where c.title = $s$Numerical Weather Prediction & Model Guidance$s$ limit 1), 4, 70, $s$2026-09-02T09:30:00+05:30$s$, $s$Good model guidance interpretation.$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/CWC/AB-31$s$ limit 1), (select e.id from public.exam_questionnaires e join public.courses c on c.id = e.course_id where c.title = $s$Satellite Remote Sensing for Weather Forecasting$s$ limit 1), 3, 55, $s$2026-09-11T13:15:00+05:30$s$, $s$Retake advised: sounder product assimilation.$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/MUM/RL-18$s$ limit 1), (select e.id from public.exam_questionnaires e join public.courses c on c.id = e.course_id where c.title = $s$Radar Meteorology & Doppler Data Interpretation$s$ limit 1), 4, 85, $s$2026-09-03T15:20:00+05:30$s$, $s$Excellent Doppler interpretation.$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/MUM/RL-18$s$ limit 1), (select e.id from public.exam_questionnaires e join public.courses c on c.id = e.course_id where c.title = $s$Cyclone Tracking & Warning Systems$s$ limit 1), 3, 64, $s$2026-09-05T11:40:00+05:30$s$, $s$Competent; revise intensification thresholds.$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/MUM/RL-18$s$ limit 1), (select e.id from public.exam_questionnaires e join public.courses c on c.id = e.course_id where c.title = $s$Satellite Remote Sensing for Weather Forecasting$s$ limit 1), 4, 72, $s$2026-09-07T14:55:00+05:30$s$, $s$Good precipitation estimation technique.$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/MUM/RL-18$s$ limit 1), (select e.id from public.exam_questionnaires e join public.courses c on c.id = e.course_id where c.title = $s$Agro-Meteorology & Crop-Weather Advisory$s$ limit 1), 3, 80, $s$2026-09-09T09:20:00+05:30$s$, $s$Strong crop-weather advisory skills.$s$),
  ((select id from public.user_profiles where employee_id = $s$IMD/MUM/RL-18$s$ limit 1), (select e.id from public.exam_questionnaires e join public.courses c on c.id = e.course_id where c.title = $s$Numerical Weather Prediction & Model Guidance$s$ limit 1), 3, 58, $s$2026-09-11T16:05:00+05:30$s$, $s$Retake required: bias-correction methods.$s$)
on conflict (trainee_id, exam_id, completion_date) do nothing;

-- ===================== 7. BULLETINS =================================
insert into public.homepage_bulletins (type, title, message, published_by, date_created) values
  ($s$Notification$s$, $s$CWC shift rosters updated for monsoon withdrawal$s$, $s$All Cyclone Warning Centre staff are requested to confirm their shift allocations before week-end.$s$, (select id from public.user_profiles where employee_id = $s$IMD/HQ/MMOHAP-01$s$ limit 1), $s$2026-09-08T09:00:00+05:30$s$),
  ($s$Announcement$s$, $s$IMD joins Monsoon Mission Phase-III review$s$, $s$Training on ensemble prediction tools will be integrated into the next NWP cohort.$s$, (select id from public.user_profiles where employee_id = $s$IMD/HQ/SRAO-15$s$ limit 1), $s$2026-09-07T11:30:00+05:30$s$),
  ($s$Achievement$s$, $s$Doppler radar upgradation at Mumbai completed$s$, $s$Regional Meteorological Centre Mumbai now streams Level-II DWR products to forecasters.$s$, (select id from public.user_profiles where employee_id = $s$IMD/HQ/MMOHAP-01$s$ limit 1), $s$2026-09-06T16:00:00+05:30$s$),
  ($s$New Content$s$, $s$Satellite Remote Sensing module refreshed$s$, $s$INSAT-3DS algorithm updates added to the Satellite Remote Sensing course.$s$, (select id from public.user_profiles where employee_id = $s$IMD/HQ/SRAO-15$s$ limit 1), $s$2026-09-05T10:15:00+05:30$s$),
  ($s$New Content$s$, $s$Climate Modelling reading list updated$s$, $s$IITM ensemble hindcast papers and NCUM-LAM monsoon diagnostics added to the Climate Modelling course library.$s$, (select id from public.user_profiles where employee_id = $s$IMD/HQ/AP-09$s$ limit 1), $s$2026-09-09T09:30:00+05:30$s$),
  ($s$Achievement$s$, $s$Hyderabad DWR annual calibration milestone achieved$s$, $s$All 3 Doppler Weather Radars in the southern peninsula pass annual calibration benchmarks.$s$, (select id from public.user_profiles where employee_id = $s$IMD/HYD/VK-55$s$ limit 1), $s$2026-09-09T14:45:00+05:30$s$),
  ($s$Notification$s$, $s$Mandatory SAFAR air-quality data submission$s$, $s$All stations with ambient air quality instruments must upload hourly PM2.5/PM10 datasets before 12 September.$s$, (select id from public.user_profiles where employee_id = $s$IMD/HQ/MMOHAP-01$s$ limit 1), $s$2026-09-10T08:30:00+05:30$s$),
  ($s$Announcement$s$, $s$NWP cohort 4 enrolment opens next week$s$, $s$All commissioned meteorologists may register for the Numerical Weather Prediction module from 14 September.$s$, (select id from public.user_profiles where employee_id = $s$IMD/HQ/SRAO-15$s$ limit 1), $s$2026-09-10T11:15:00+05:30$s$),
  ($s$Achievement$s$, $s$IMD-IITM monsoon hindcast paper accepted$s$, $s$Coupled model evaluation paper by Dr. Anita Joshi accepted for publication in Climate Dynamics journal.$s$, (select id from public.user_profiles where employee_id = $s$IMD/HQ/AP-09$s$ limit 1), $s$2026-09-11T09:00:00+05:30$s$),
  ($s$Notification$s$, $s$DWR preventive maintenance window Sep 14$s$, $s$East Coast radar stations will undergo scheduled maintenance on 14 September 08:00-14:00 IST.$s$, (select id from public.user_profiles where employee_id = $s$IMD/HYD/VK-55$s$ limit 1), $s$2026-09-11T10:30:00+05:30$s$)
  on conflict (title, message) do nothing;

commit;